name: Access secrets

on:
  workflow_dispatch:

jobs:

  deploy_app_in_dev:
    runs-on: ubuntu-latest

    steps:
    - name: Get the AWS credentials from Google Secret Manager
      id: gcp_secrets
      uses: google-github-actions/get-secretmanager-secrets@main
      with:
        credentials: ${{ secrets.GCP_SA_KEY }}
        secrets: |-
          AWS_ACCESS_KEY_ID:${{ secrets.GCP_PROJECT_ID }}/AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY:${{ secrets.GCP_PROJECT_ID }}/AWS_SECRET_ACCESS_KEY

    - name: Print secret
      run: echo ${{ steps.gcp_secrets.outputs.AWS_ACCESS_KEY_ID }}