name: Copy aws
on:
  workflow_dispatch:

jobs:

  deploy_app_in_dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Get the AWS credentials from Google Secret Manager
        id: gcp_secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          secrets: |-
            AWS_ACCESS_KEY_ID:${{ secrets.GCP_PROJECT_ID }}/AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY:${{ secrets.GCP_PROJECT_ID }}/AWS_SECRET_ACCESS_KEY
      
      - name: Copy the files that are not pushed on GitHub
        uses: prewk/s3-cp-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.gcp_secrets.outputs.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.gcp_secrets.outputs.AWS_SECRET_ACCESS_KEY }}
          SOURCE: 's3://age-prediction-site/flavicon.ico'
          DEST: './data/'

      - name: View
        run: ls -a